[package]
name = "espresso-derivation-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = { workspace = true }
ark-serialize = { workspace = true }
serde = { workspace = true }
committable = { workspace = true }
either = { workspace = true }
jf-merkle-tree = { workspace = true }
jf-vid = { workspace = true }
sha2 = { workspace = true }
primitive-types = { workspace = true }
