[package]
version = "0.1.0"
name = "espresso-derivation-prover"
edition = "2021"

[[bin]]
name = "prove"
path = "src/bin/prove.rs"

[dependencies]
alloy-sol-types = "0.7.2"
clap = { version = "4.0", features = ["derive", "env"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.7-testnet" }
tracing = "0.1.40"
espresso-derivation-utils = { path = "../utils" }

[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.7-testnet" }
